_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 23
                - 55
                - 61
            "4": 3.12.8
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
